POST http://localhost:3002/exercises HTTP/1.1
content-type: application/json

{
  "daily_exercises": [9,8,7,6,4,2,0,5,0,10],
  "target": 5.4
}

###
POST http://localhost:3002/exercises HTTP/1.1
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

###
POST http://localhost:3002/exercises HTTP/1.1
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5]
}

###
POST http://localhost:3002/exercises HTTP/1.1
content-type: application/json

{
  "daily_exercises": [1],
  "target": "lol"
}