POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Testi Tyyppi",
  "dateOfBirth": "1991-02-14",
  "ssn": "140291-1123",
  "gender": "male",
  "occupation": "Student"
}