POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Testi Tyyppi",
  "dateOfBirth": "14-02-1991",
  "ssn": "140291-1123",
  "gender": "Male",
  "occupation": "Student"
}